export const EstablishmentTypesData = [
  {
    key: "1",
    id: "1",
    type: "Pizzeria",
    No_Categories: "5",
    Date: "15 Nov 2025",
    Status: "Active",
    image: "establishment-type-01.png",
  },
  {
    key: "2",
    id: "2",
    type: "Snack",
    No_Categories: "3",
    Date: "14 Nov 2025",
    Status: "Active",
    image: "establishment-type-02.png",
  },
  {
    key: "3",
    id: "3",
    type: "Friterie",
    No_Categories: "2",
    Date: "13 Nov 2025",
    Status: "Active",
    image: "establishment-type-03.png",
  },
  {
    key: "4",
    id: "4",
    type: "Restaurant",
    No_Categories: "8",
    Date: "12 Nov 2025",
    Status: "Active",
    image: "establishment-type-04.png",
  },
  {
    key: "5",
    id: "5",
    type: "Gastro Restaurant",
    No_Categories: "10",
    Date: "11 Nov 2025",
    Status: "Active",
    image: "establishment-type-05.png",
  },
];
